// app/src/app/features/marketplace/marketplace.component.ts
import { Component, signal, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { EcoApiService, MarketListing } from '../../services/eco-api.service';

@Component({
  selector: 'app-marketplace',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="max-w-6xl mx-auto p-6">
      <div class="flex justify-between items-center mb-8">
        <h2 class="text-3xl font-bold text-stone-800">Community Market</h2>
        <button (click)="showForm.set(!showForm())" class="bg-stone-900 text-white px-6 py-2 rounded-lg">
          {{ showForm() ? 'Cancel' : 'Post Item' }}
        </button>
      </div>

      @if (showForm()) {
        <div class="bg-white p-6 rounded-xl shadow-lg mb-8 border border-stone-200">
          <form (ngSubmit)="submitListing()" class="grid md:grid-cols-2 gap-4">
            <input [(ngModel)]="newItem.title" name="title" placeholder="Title" class="p-3 border rounded">
            <input [(ngModel)]="newItem.price" name="price" placeholder="Price" class="p-3 border rounded">
            <input [(ngModel)]="newItem.contact" name="contact" placeholder="Email" class="p-3 border rounded">
            <button type="submit" class="bg-emerald-600 text-white p-3 rounded font-bold">Post Listing</button>
          </form>
        </div>
      }

      <div class="grid md:grid-cols-4 gap-6">
        @for (item of listings(); track item._id) {
          <div class="bg-white p-4 rounded-xl border border-stone-200 hover:shadow-md transition-shadow">
            <div class="text-4xl mb-4 bg-stone-50 h-32 flex items-center justify-center rounded-lg">{{ item.emoji || '📦' }}</div>
            <h3 class="font-bold text-lg truncate">{{ item.title }}</h3>
            <div class="flex justify-between mt-2">
              <span class="text-emerald-600 font-bold">{{ item.price }}</span>
              <span class="text-xs text-stone-400">{{ item.condition }}</span>
            </div>
          </div>
        }
      </div>
    </div>
  `
})
export class MarketplaceComponent implements OnInit {
  private api = inject(EcoApiService);

  listings = signal<MarketListing[]>([]);
  showForm = signal(false);
  newItem: any = { title: '', price: '', contact: '', condition: 'Good', emoji: '📦' };

  ngOnInit() {
    this.loadListings();
  }

  loadListings() {
    this.api.getListings().subscribe(data => this.listings.set(data));
  }

  submitListing() {
    this.api.createListing(this.newItem).subscribe(created => {
      this.listings.update(prev => [created, ...prev]);
      this.showForm.set(false);
    });
  }
}

// app/src/app/features/marketplace/Marketplace.tsx
import { useState, useEffect } from 'react';
import { ecoApiService, MarketListing } from '../../services/eco-api.service';

function Marketplace() {
  const [listings, setListings] = useState<MarketListing[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [newItem, setNewItem] = useState({ title: '', price: '', contact: '', condition: 'Good', emoji: '📦' });

  useEffect(() => {
    loadListings();
  }, []);

  const loadListings = async () => {
    try {
      const data = await ecoApiService.getListings();
      setListings(data);
    } catch (error) {
      console.error('Failed to load listings:', error);
    }
  };

  const submitListing = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const created = await ecoApiService.createListing(newItem);
      setListings(prev => [created, ...prev]);
      setShowForm(false);
      setNewItem({ title: '', price: '', contact: '', condition: 'Good', emoji: '📦' });
    } catch (error) {
      console.error('Failed to create listing:', error);
    }
  };

  return (
    <div className="max-w-6xl mx-auto p-6">
      <div className="flex justify-between items-center mb-8">
        <h2 className="text-3xl font-bold text-stone-800">Community Market</h2>
        <button 
          onClick={() => setShowForm(!showForm)} 
          className="bg-stone-900 text-white px-6 py-2 rounded-lg"
        >
          {showForm ? 'Cancel' : 'Post Item'}
        </button>
      </div>

      {showForm && (
        <div className="bg-white p-6 rounded-xl shadow-lg mb-8 border border-stone-200">
          <form onSubmit={submitListing} className="grid md:grid-cols-2 gap-4">
            <input 
              value={newItem.title}
              onChange={(e) => setNewItem({...newItem, title: e.target.value})}
              placeholder="Title" 
              className="p-3 border rounded"
              required
            />
            <input 
              value={newItem.price}
              onChange={(e) => setNewItem({...newItem, price: e.target.value})}
              placeholder="Price" 
              className="p-3 border rounded"
              required
            />
            <input 
              value={newItem.contact}
              onChange={(e) => setNewItem({...newItem, contact: e.target.value})}
              placeholder="Email" 
              className="p-3 border rounded"
              type="email"
              required
            />
            <button type="submit" className="bg-emerald-600 text-white p-3 rounded font-bold">Post Listing</button>
          </form>
        </div>
      )}

      <div className="grid md:grid-cols-4 gap-6">
        {listings.map((item) => (
          <div key={item._id} className="bg-white p-4 rounded-xl border border-stone-200 hover:shadow-md transition-shadow">
            <div className="text-4xl mb-4 bg-stone-50 h-32 flex items-center justify-center rounded-lg">{item.emoji || '📦'}</div>
            <h3 className="font-bold text-lg truncate">{item.title}</h3>
            <div className="flex justify-between mt-2">
              <span className="text-emerald-600 font-bold">{item.price}</span>
              <span className="text-xs text-stone-400">{item.condition}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Marketplace;
